export enum DIFF_TYPE {
    CREATE,
    REMOVE,
    REPLACE,
    UPDATE,
    SET_PROP,
    REMOVE_PROP,
    SET_EVENT,
    REPLACE_EVENT,
    REMOVE_EVENT,
};

export type PROP_DIFF_TYPE = DIFF_TYPE.SET_PROP | DIFF_TYPE.REMOVE_PROP | DIFF_TYPE.SET_EVENT | DIFF_TYPE.REPLACE_EVENT | DIFF_TYPE.REMOVE_EVENT;