export enum DIFF_TYPE {
    CREATE = 'CREATE',
    REMOVE = 'REMOVE',
    REPLACE = 'REPLACE',
    UPDATE = 'UPDATE',
    SET_PROP = 'SET_PROP',
    REMOVE_PROP = 'REMOVE PROP',
    SET_EVENT = 'SET EVENT',
    REPLACE_EVENT = 'REPLACE EVENT',
    REMOVE_EVENT = 'REMOVE EVENT',
};